//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cerime
    {
        public int CerimeID { get; set; }

        [Display(Name = "Cərimənin Məbləği")]
        public decimal Mebleg { get; set; }

        [Display(Name = "Ödənilibmi")]
        public bool Odenilibmi { get; set; }

        [Display(Name = "Cərimələnmə Tarixi")]
        [Required(ErrorMessage = "Cərimələnmə tarixini qeyd edin!")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public System.DateTime CerimeTarixi { get; set; }

        [Display(Name = "Ödənmə Tarixi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> OdenmeTarixi { get; set; }

        [Display(Name = "Cərimələnmə Səbəbi")]
        [Required(ErrorMessage = "Boş buraxılmamalıdır!")]
        public string Sebeb { get; set; } // "Gecikir", "İtirilib"

        [Required(ErrorMessage = "Boş buraxılmamalıdır!")]
        public int IstifadechiID { get; set; }

        [Required(ErrorMessage = "Boş buraxılmamalıdır!")]
        public int IcareID { get; set; }

    
        public virtual Icare Icare { get; set; }


        public virtual Istifadechi Istifadechi { get; set; }
    }
}
