//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Elaqe
    {
        public int ElaqeID { get; set; }

        [EmailAddress, StringLength(50), Required]
        public string Email { get; set; }

        [StringLength(50), Required]
        [DisplayName("Adı")]
        public string Adi { get; set; }

        [StringLength(50)]
        [DisplayName("Soyadı")]
        public string Soyadi { get; set; }

        [Required]
        public string Mesaj { get; set; }

        [DisplayName("Göndərilmə Tarixi")]
        public System.DateTime ElaqeTarixi { get; set; }
    }
}
