//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Icare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Icare()
        {
            this.Cerime = new HashSet<Cerime>();
        }
    
        public int IcareID { get; set; }

        [Display(Name = "İcarə Qiyməti")]
        public Nullable<decimal> IcareQiymeti { get; set; }

        [Display(Name = "İcarə Tarixi")]
        public System.DateTime IcareTarixi { get; set; }

        [Display(Name = "Son Tarix")]
        public System.DateTime SonTarix { get; set; }

        [Display(Name = "Qaytarılma Tarixi")]
        public Nullable<System.DateTime> QaytarilmaTarixi { get; set; }

        [Display(Name = "Qaytarılıb")]
        public bool Qaytarilibmi { get; set; }

        [Display(Name = "İcarənin Status")]
        public string Statusu { get; set; } // Aktiv, Gecikir, Qaytarılıb

        public int IstifadechiID { get; set; }

        public int KitabID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cerime> Cerime { get; set; }

        public virtual Istifadechi Istifadechi { get; set; }
        public virtual Kitab Kitab { get; set; }
    }
}
