//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Istifadechi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Istifadechi()
        {
            this.Cerime = new HashSet<Cerime>();
            this.Icare = new HashSet<Icare>();
        }
    
        public int IstifadechiID { get; set; }

        [Display(Name = "Adı")]
        [Required(ErrorMessage = "Ad mütləqdir!")]
        public string Adi { get; set; }

        [Display(Name = "Soyadı")]
        [Required(ErrorMessage = "Soyad mütləqdir!")]
        public string Soyadi { get; set; }

        [Display(Name = "Doğum Tarixi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Doğum tarixini daxil edin!")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DoghumTarixi { get; set; }

        [Display(Name = "Cinsi")]
        public string Cins { get; set; }

        [Display(Name = "FİN")]
        [Required(ErrorMessage = "FİN mütləqdir!")]
        [StringLength(7, ErrorMessage = "FİN kod maksimum 7 simvol ola bilər!")]
        public string FinKod { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email mütləqdir!")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Email formata uyğun deyil!")]
        public string Email { get; set; }

        [Display(Name = "Əlaqə Nömrəsi")]
        [RegularExpression(@"^\d{10}$")]
        [StringLength(10, ErrorMessage = "Əlaqə nömrəsi maksimum 10 rəqəmdən ibarət ola bilər!")]
        public string TelefonNo { get; set; }

        [Display(Name = "Ünvan")]
        public string Adres { get; set; }

        [Display(Name = "İstifadəçi Adı")]
        [Required(ErrorMessage = "İstifadəçi Adı təyin olunmalıdır!")]
        public string IstifadechiAdi { get; set; }

        [Display(Name = "Şifrə")]
        [MinLength(6)]
        [Required(ErrorMessage = "Şifrə minimum 6 simvoldan ibarət olmalıdır")]
        public string Shifre { get; set; }

        [Display(Name = "Aktivdir")]
        public bool Aktivdirmi { get; set; }
        //public Nullable<bool> Aktivdirmi { get; set; }

        [Display(Name = "Qeydiyyat Tarixi")]
        public Nullable<System.DateTime> QeydiyyatTarixi { get; set; }

        [Display(Name = "Rolu")]
        [Required(ErrorMessage = "İstifadəçinin rolunu təyin edin!")]
        public int RolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cerime> Cerime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icare> Icare { get; set; }

        public virtual Rol Rol { get; set; }
    }
}
