//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Istifadechi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Istifadechi()
        {
            this.Cerime = new HashSet<Cerime>();
            this.Icare = new HashSet<Icare>();
        }
    
        public int IstifadechiID { get; set; }

        [Display(Name = "Adı")]
        public string Adi { get; set; }

        [Display(Name = "Soyadı")]
        public string Soyadi { get; set; }

        [Display(Name = "İstifadəçi")]
        public string AdSoyadi
        {
            get { return Adi + " " + Soyadi; }
        }

        [Display(Name = "Doğum Tarixi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DoghumTarixi { get; set; }

        [Display(Name = "Cinsi")]
        public string Cins { get; set; }

        [Display(Name = "FİN")]
        public string FinKod { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Əlaqə Nömrəsi")]
        public string TelefonNo { get; set; }

        [Display(Name = "Ünvan")]
        public string Adres { get; set; }

        [Display(Name = "İstifadəçi Adı")]
        public string IstifadechiAdi { get; set; }

        [Display(Name = "Şifrə")]
        public string Shifre { get; set; }

        [Display(Name = "Aktivdir")]
        public bool Aktivdirmi { get; set; }
        //public Nullable<bool> Aktivdirmi { get; set; }

        [Display(Name = "Qeydiyyat Tarixi")]
        public Nullable<System.DateTime> QeydiyyatTarixi { get; set; }

        [Display(Name = "Rolu")]
        public int RolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cerime> Cerime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icare> Icare { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
