//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kateqoriya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kateqoriya()
        {
            this.Kitab = new HashSet<Kitab>();
        }
    
        public int KateqoriyaID { get; set; }

        [Display(Name = "Kateqoriyanın Adı")]
        public string KateqoriyaAdi { get; set; }

        [Display(Name = "Kateqoriya Haqqında")]
        public string KateqoriyaTesviri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitab> Kitab { get; set; }
    }
}
