//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kitab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitab()
        {
            this.Icare = new HashSet<Icare>();
        }
    
        public int KitabID { get; set; }

        [Display(Name = "Kitab")]
        [Required(ErrorMessage = "Boş buraxılmamalıdır!")]
        public string KitabAdi { get; set; }

        [Display(Name = "Müəllif")]
        [Required(ErrorMessage = "Müəllif təyin edin!")]
        public int MuellifID { get; set; }

        [Display(Name = "Kateqoriya")]
        [Required(ErrorMessage = "Kateqoriya təyin edin!")]
        public int KateqoriyaID { get; set; }

        [Display(Name = "İcarə Qiyməti")]
        public Nullable<decimal> IcareQiymeti { get; set; }

        [Display(Name = "Stokda Var")]
        public bool StokdaVarmi { get; set; }

        [Display(Name = "Haqqında")]
        public string Haqqinda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icare> Icare { get; set; }
        public virtual Kateqoriya Kateqoriya { get; set; }
        public virtual Muellif Muellif { get; set; }
    }
}
