//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagementSystemDBEntities : DbContext
    {
        public LibraryManagementSystemDBEntities()
            : base("name=LibraryManagementSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cerime> Cerime { get; set; }
        public virtual DbSet<Icare> Icare { get; set; }
        public virtual DbSet<Istifadechi> Istifadechi { get; set; }
        public virtual DbSet<Kateqoriya> Kateqoriya { get; set; }
        public virtual DbSet<Kitab> Kitab { get; set; }
        public virtual DbSet<Muellif> Muellif { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
    }
}
