//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Muellif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Muellif()
        {
            this.Kitab = new HashSet<Kitab>();
        }
    
        public int MuellifID { get; set; }

        [Display(Name = "Müəllifin Adı")]
        [Required(ErrorMessage = "Ad mütləqdir!")]
        public string MuellifAdi { get; set; }

        [Display(Name = "Müəllifin Soyadı")]
        [Required(ErrorMessage = "Soyad mütləqdir!")]
        public string MuellifSoyadi { get; set; }
        public string MuellifAdSoyadi
        {
            get { return MuellifAdi + " " + MuellifSoyadi; }
        }

        [Display(Name = "Müəllifin Doğum Tarixi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> MuellifinDoghumTarixi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitab> Kitab { get; set; }
    }
}
