//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Slider
    {
        public int SliderID { get; set; }

        [Display(Name = "Başlıq")]
        [Required(ErrorMessage = "Başlıq daxil edilməlidir!")]
        [StringLength(255, ErrorMessage = "Başlıq maksimum 255 simvol ola bilər!")]
        public string Bashliq { get; set; }

        [Display(Name = "Açıqlama")]
        [StringLength(4000)]
        public string Achiqlama { get; set; }

        [Url]
        public string Link { get; set; }

        [Display(Name = "Şəkil")]
        public string Sekil { get; set; }
    }
}
